services:

  n8n:
    image: n8nio/n8n
    container_name: n8n_responder
    restart: always
    ports:
      - "5678:5678"

    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false

    volumes:
      - n8n_data:/home/node/.n8n

    mem_limit: 4g

    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama_responder
    restart: always

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

volumes:
  n8n_data:
  ollama_data: